# MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bus_reservation_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# VNPay
vnp_Version=2.1.0
vnp_Command=pay
vnp_TmnCode=FFBQEIAJ
vnp_HashSecret=7HNOYVGJRDGFI2NZ64OXYF7G3K1J0EN5
vnp_Url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_ReturnURL=http://localhost:8080/payment/vnpay-return
vnp.api_Url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# RabbitMQ

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

rabbitmq.queue.order.name=order_queue
rabbitmq.exchange.name=order_exchange
rabbitmq.binding.routing.key=order_routing_key

# Spring mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis
redis.host=${SPRING_DATA_REDIS_HOST:localhost}
redis.port=${SPRING_DATA_REDIS_PORT:6379}


# JWT
app.jwtSecret=b1068bfd7cf9176967f1932b09de8d8d25d0c34af766704bc4544e8b0c2270f4
# 24h
app.accessTokenExpiration=86400000
# refresh token 5p
app.refreshTokenExpiration=300000

# Spring AI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.application.name=travelK-bus_ticket_booking
management.endpoints.web.exposure.include=*
